import type { Airport } from "./types";

export const POPULAR_IATA = [
  "CDG",
  "ORY",
  "LHR",
  "AMS",
  "JFK",
  "LAX",
  "DXB",
  "SIN",
  "HND",
  "MAD",
  "FCO",
  "IST",
];

export const AIRPORTS: Airport[] = [
  { iata: "CDG", city: "Paris", name: "Charles de Gaulle", country: "France" },
  { iata: "ORY", city: "Paris", name: "Orly", country: "France" },
  { iata: "BVA", city: "Paris", name: "Beauvais-Tillé", country: "France" },
  { iata: "LYS", city: "Lyon", name: "Saint-Exupéry", country: "France" },
  { iata: "MRS", city: "Marseille", name: "Provence", country: "France" },
  { iata: "NCE", city: "Nice", name: "Côte d'Azur", country: "France" },
  { iata: "TLS", city: "Toulouse", name: "Blagnac", country: "France" },
  { iata: "NTE", city: "Nantes", name: "Atlantique", country: "France" },
  { iata: "BOD", city: "Bordeaux", name: "Mérignac", country: "France" },
  { iata: "LIL", city: "Lille", name: "Lesquin", country: "France" },
  { iata: "SXB", city: "Strasbourg", name: "Entzheim", country: "France" },
  { iata: "MPL", city: "Montpellier", name: "Méditerranée", country: "France" },
  { iata: "RNS", city: "Rennes", name: "Saint-Jacques", country: "France" },
  { iata: "BIQ", city: "Biarritz", name: "Pays Basque", country: "France" },
  { iata: "PGF", city: "Perpignan", name: "Rivesaltes", country: "France" },
  { iata: "AJA", city: "Ajaccio", name: "Napoléon Bonaparte", country: "France" },
  { iata: "BIA", city: "Bastia", name: "Poretta", country: "France" },
  { iata: "FSC", city: "Figari", name: "Sud Corse", country: "France" },
  { iata: "CFR", city: "Caen", name: "Carpiquet", country: "France" },
  { iata: "LHR", city: "Londres", name: "Heathrow", country: "Royaume-Uni" },
  { iata: "LGW", city: "Londres", name: "Gatwick", country: "Royaume-Uni" },
  { iata: "STN", city: "Londres", name: "Stansted", country: "Royaume-Uni" },
  { iata: "LTN", city: "Londres", name: "Luton", country: "Royaume-Uni" },
  { iata: "LCY", city: "Londres", name: "City", country: "Royaume-Uni" },
  { iata: "MAN", city: "Manchester", name: "Manchester", country: "Royaume-Uni" },
  { iata: "EDI", city: "Édimbourg", name: "Edinburgh", country: "Royaume-Uni" },
  { iata: "BHX", city: "Birmingham", name: "Birmingham", country: "Royaume-Uni" },
  { iata: "GLA", city: "Glasgow", name: "Glasgow", country: "Royaume-Uni" },
  { iata: "DUB", city: "Dublin", name: "Dublin", country: "Irlande" },
  { iata: "SNN", city: "Shannon", name: "Shannon", country: "Irlande" },
  { iata: "AMS", city: "Amsterdam", name: "Schiphol", country: "Pays-Bas" },
  { iata: "RTM", city: "Rotterdam", name: "The Hague", country: "Pays-Bas" },
  { iata: "BRU", city: "Bruxelles", name: "Zaventem", country: "Belgique" },
  { iata: "CRL", city: "Charleroi", name: "Bruxelles-Sud", country: "Belgique" },
  { iata: "LUX", city: "Luxembourg", name: "Findel", country: "Luxembourg" },
  { iata: "FRA", city: "Francfort", name: "Francfort", country: "Allemagne" },
  { iata: "MUC", city: "Munich", name: "Franz Josef Strauss", country: "Allemagne" },
  { iata: "BER", city: "Berlin", name: "Brandebourg", country: "Allemagne" },
  { iata: "DUS", city: "Düsseldorf", name: "Düsseldorf", country: "Allemagne" },
  { iata: "HAM", city: "Hambourg", name: "Hambourg", country: "Allemagne" },
  { iata: "CGN", city: "Cologne", name: "Bonn", country: "Allemagne" },
  { iata: "STR", city: "Stuttgart", name: "Stuttgart", country: "Allemagne" },
  { iata: "MAD", city: "Madrid", name: "Adolfo Suárez Barajas", country: "Espagne" },
  { iata: "BCN", city: "Barcelone", name: "Josep Tarradellas El Prat", country: "Espagne" },
  { iata: "AGP", city: "Malaga", name: "Costa del Sol", country: "Espagne" },
  { iata: "PMI", city: "Palma", name: "Palma de Mallorca", country: "Espagne" },
  { iata: "ALC", city: "Alicante", name: "Alicante-Elche", country: "Espagne" },
  { iata: "VLC", city: "Valence", name: "Valencia", country: "Espagne" },
  { iata: "SVQ", city: "Séville", name: "San Pablo", country: "Espagne" },
  { iata: "BIO", city: "Bilbao", name: "Bilbao", country: "Espagne" },
  { iata: "TFS", city: "Tenerife", name: "Tenerife Sud", country: "Espagne" },
  { iata: "LPA", city: "Las Palmas", name: "Gran Canaria", country: "Espagne" },
  { iata: "LIS", city: "Lisbonne", name: "Humberto Delgado", country: "Portugal" },
  { iata: "OPO", city: "Porto", name: "Francisco Sá Carneiro", country: "Portugal" },
  { iata: "FAO", city: "Faro", name: "Faro", country: "Portugal" },
  { iata: "FNC", city: "Funchal", name: "Madère", country: "Portugal" },
  { iata: "FCO", city: "Rome", name: "Leonardo da Vinci Fiumicino", country: "Italie" },
  { iata: "CIA", city: "Rome", name: "Ciampino", country: "Italie" },
  { iata: "MXP", city: "Milan", name: "Malpensa", country: "Italie" },
  { iata: "LIN", city: "Milan", name: "Linate", country: "Italie" },
  { iata: "BGY", city: "Milan", name: "Bergame Orio al Serio", country: "Italie" },
  { iata: "VCE", city: "Venise", name: "Marco Polo", country: "Italie" },
  { iata: "NAP", city: "Naples", name: "Capodichino", country: "Italie" },
  { iata: "BLQ", city: "Bologne", name: "Guglielmo Marconi", country: "Italie" },
  { iata: "FLR", city: "Florence", name: "Peretola", country: "Italie" },
  { iata: "PMO", city: "Palerme", name: "Punta Raisi", country: "Italie" },
  { iata: "CTA", city: "Catane", name: "Fontanarossa", country: "Italie" },
  { iata: "ATH", city: "Athènes", name: "Elefthérios Venizélos", country: "Grèce" },
  { iata: "HER", city: "Héraklion", name: "Nikos Kazantzakis", country: "Grèce" },
  { iata: "SKG", city: "Thessalonique", name: "Makedonia", country: "Grèce" },
  { iata: "JTR", city: "Santorin", name: "Santorin", country: "Grèce" },
  { iata: "IST", city: "Istanbul", name: "Istanbul", country: "Turquie" },
  { iata: "SAW", city: "Istanbul", name: "Sabiha Gökçen", country: "Turquie" },
  { iata: "AYT", city: "Antalya", name: "Antalya", country: "Turquie" },
  { iata: "ADB", city: "Izmir", name: "Adnan Menderes", country: "Turquie" },
  { iata: "ZRH", city: "Zurich", name: "Kloten", country: "Suisse" },
  { iata: "GVA", city: "Genève", name: "Cointrin", country: "Suisse" },
  { iata: "BSL", city: "Bâle", name: "EuroAirport", country: "Suisse" },
  { iata: "VIE", city: "Vienne", name: "Schwechat", country: "Autriche" },
  { iata: "INN", city: "Innsbruck", name: "Innsbruck", country: "Autriche" },
  { iata: "CPH", city: "Copenhague", name: "Kastrup", country: "Danemark" },
  { iata: "OSL", city: "Oslo", name: "Gardermoen", country: "Norvège" },
  { iata: "BGO", city: "Bergen", name: "Flesland", country: "Norvège" },
  { iata: "ARN", city: "Stockholm", name: "Arlanda", country: "Suède" },
  { iata: "GOT", city: "Göteborg", name: "Landvetter", country: "Suède" },
  { iata: "HEL", city: "Helsinki", name: "Vantaa", country: "Finlande" },
  { iata: "KEF", city: "Reykjavik", name: "Keflavík", country: "Islande" },
  { iata: "WAW", city: "Varsovie", name: "Chopin", country: "Pologne" },
  { iata: "KRK", city: "Cracovie", name: "Jean-Paul II", country: "Pologne" },
  { iata: "PRG", city: "Prague", name: "Václav Havel", country: "Tchéquie" },
  { iata: "BUD", city: "Budapest", name: "Ferenc Liszt", country: "Hongrie" },
  { iata: "OTP", city: "Bucarest", name: "Henri Coandă", country: "Roumanie" },
  { iata: "SOF", city: "Sofia", name: "Sofia", country: "Bulgarie" },
  { iata: "BEG", city: "Belgrade", name: "Nikola Tesla", country: "Serbie" },
  { iata: "ZAG", city: "Zagreb", name: "Franjo Tuđman", country: "Croatie" },
  { iata: "DBV", city: "Dubrovnik", name: "Dubrovnik", country: "Croatie" },
  { iata: "SPU", city: "Split", name: "Split", country: "Croatie" },
  { iata: "LJU", city: "Ljubljana", name: "Jože Pučnik", country: "Slovénie" },
  { iata: "TIA", city: "Tirana", name: "Nënë Tereza", country: "Albanie" },
  { iata: "SKP", city: "Skopje", name: "Skopje", country: "Macédoine du Nord" },
  { iata: "RIX", city: "Riga", name: "Riga", country: "Lettonie" },
  { iata: "VNO", city: "Vilnius", name: "Vilnius", country: "Lituanie" },
  { iata: "TLL", city: "Tallinn", name: "Lennart Meri", country: "Estonie" },
  { iata: "KBP", city: "Kyiv", name: "Boryspil", country: "Ukraine" },
  { iata: "MSQ", city: "Minsk", name: "Minsk", country: "Biélorussie" },
  { iata: "SVO", city: "Moscou", name: "Sheremetyevo", country: "Russie" },
  { iata: "DME", city: "Moscou", name: "Domodedovo", country: "Russie" },
  { iata: "LED", city: "Saint-Pétersbourg", name: "Poulkovo", country: "Russie" },
  { iata: "TBS", city: "Tbilissi", name: "Tbilissi", country: "Géorgie" },
  { iata: "EVN", city: "Erevan", name: "Zvartnots", country: "Arménie" },
  { iata: "GYD", city: "Bakou", name: "Heydar Aliyev", country: "Azerbaïdjan" },
  { iata: "JFK", city: "New York", name: "John F. Kennedy", country: "États-Unis" },
  { iata: "EWR", city: "New York", name: "Newark Liberty", country: "États-Unis" },
  { iata: "LGA", city: "New York", name: "LaGuardia", country: "États-Unis" },
  { iata: "LAX", city: "Los Angeles", name: "Los Angeles International", country: "États-Unis" },
  { iata: "SFO", city: "San Francisco", name: "San Francisco International", country: "États-Unis" },
  { iata: "ORD", city: "Chicago", name: "O'Hare", country: "États-Unis" },
  { iata: "MDW", city: "Chicago", name: "Midway", country: "États-Unis" },
  { iata: "MIA", city: "Miami", name: "Miami International", country: "États-Unis" },
  { iata: "FLL", city: "Fort Lauderdale", name: "Hollywood", country: "États-Unis" },
  { iata: "MCO", city: "Orlando", name: "Orlando International", country: "États-Unis" },
  { iata: "ATL", city: "Atlanta", name: "Hartsfield-Jackson", country: "États-Unis" },
  { iata: "DFW", city: "Dallas", name: "Dallas/Fort Worth", country: "États-Unis" },
  { iata: "IAH", city: "Houston", name: "George Bush", country: "États-Unis" },
  { iata: "SEA", city: "Seattle", name: "Tacoma", country: "États-Unis" },
  { iata: "BOS", city: "Boston", name: "Logan", country: "États-Unis" },
  { iata: "IAD", city: "Washington", name: "Dulles", country: "États-Unis" },
  { iata: "DCA", city: "Washington", name: "Ronald Reagan", country: "États-Unis" },
  { iata: "PHL", city: "Philadelphie", name: "Philadelphia", country: "États-Unis" },
  { iata: "LAS", city: "Las Vegas", name: "Harry Reid", country: "États-Unis" },
  { iata: "PHX", city: "Phoenix", name: "Sky Harbor", country: "États-Unis" },
  { iata: "DEN", city: "Denver", name: "Denver International", country: "États-Unis" },
  { iata: "MSP", city: "Minneapolis", name: "Saint Paul", country: "États-Unis" },
  { iata: "DTW", city: "Détroit", name: "Wayne County", country: "États-Unis" },
  { iata: "CLT", city: "Charlotte", name: "Douglas International", country: "États-Unis" },
  { iata: "HNL", city: "Honolulu", name: "Daniel K. Inouye", country: "États-Unis" },
  { iata: "SAN", city: "San Diego", name: "San Diego", country: "États-Unis" },
  { iata: "YUL", city: "Montréal", name: "Pierre Elliott Trudeau", country: "Canada" },
  { iata: "YYZ", city: "Toronto", name: "Pearson", country: "Canada" },
  { iata: "YVR", city: "Vancouver", name: "Vancouver International", country: "Canada" },
  { iata: "YYC", city: "Calgary", name: "Calgary", country: "Canada" },
  { iata: "YOW", city: "Ottawa", name: "Macdonald-Cartier", country: "Canada" },
  { iata: "YQB", city: "Québec", name: "Jean Lesage", country: "Canada" },
  { iata: "MEX", city: "Mexico", name: "Benito Juárez", country: "Mexique" },
  { iata: "CUN", city: "Cancún", name: "Cancún", country: "Mexique" },
  { iata: "GDL", city: "Guadalajara", name: "Miguel Hidalgo", country: "Mexique" },
  { iata: "HAV", city: "La Havane", name: "José Martí", country: "Cuba" },
  { iata: "PUJ", city: "Punta Cana", name: "Punta Cana", country: "République dominicaine" },
  { iata: "SDQ", city: "Saint-Domingue", name: "Las Américas", country: "République dominicaine" },
  { iata: "NAS", city: "Nassau", name: "Lynden Pindling", country: "Bahamas" },
  { iata: "MBJ", city: "Montego Bay", name: "Sangster", country: "Jamaïque" },
  { iata: "GRU", city: "São Paulo", name: "Guarulhos", country: "Brésil" },
  { iata: "CGH", city: "São Paulo", name: "Congonhas", country: "Brésil" },
  { iata: "GIG", city: "Rio de Janeiro", name: "Galeão", country: "Brésil" },
  { iata: "BSB", city: "Brasilia", name: "Presidente Juscelino Kubitschek", country: "Brésil" },
  { iata: "SSA", city: "Salvador", name: "Deputado Luís Eduardo Magalhães", country: "Brésil" },
  { iata: "EZE", city: "Buenos Aires", name: "Ministro Pistarini Ezeiza", country: "Argentine" },
  { iata: "AEP", city: "Buenos Aires", name: "Jorge Newbery", country: "Argentine" },
  { iata: "SCL", city: "Santiago", name: "Arturo Merino Benítez", country: "Chili" },
  { iata: "LIM", city: "Lima", name: "Jorge Chávez", country: "Pérou" },
  { iata: "BOG", city: "Bogotá", name: "El Dorado", country: "Colombie" },
  { iata: "MDE", city: "Medellín", name: "José María Córdova", country: "Colombie" },
  { iata: "UIO", city: "Quito", name: "Mariscal Sucre", country: "Équateur" },
  { iata: "CCS", city: "Caracas", name: "Simón Bolívar", country: "Venezuela" },
  { iata: "PTY", city: "Panama", name: "Tocumen", country: "Panama" },
  { iata: "SJO", city: "San José", name: "Juan Santamaría", country: "Costa Rica" },
  { iata: "MVD", city: "Montevideo", name: "Carrasco", country: "Uruguay" },
  { iata: "ASU", city: "Asunción", name: "Silvio Pettirossi", country: "Paraguay" },
  { iata: "LPB", city: "La Paz", name: "El Alto", country: "Bolivie" },
  { iata: "CMN", city: "Casablanca", name: "Mohammed V", country: "Maroc" },
  { iata: "RAK", city: "Marrakech", name: "Ménara", country: "Maroc" },
  { iata: "AGA", city: "Agadir", name: "Al Massira", country: "Maroc" },
  { iata: "TNG", city: "Tanger", name: "Ibn Battouta", country: "Maroc" },
  { iata: "FEZ", city: "Fès", name: "Fès-Saïss", country: "Maroc" },
  { iata: "RBA", city: "Rabat", name: "Salé", country: "Maroc" },
  { iata: "OUD", city: "Oujda", name: "Angads", country: "Maroc" },
  { iata: "TUN", city: "Tunis", name: "Carthage", country: "Tunisie" },
  { iata: "DJE", city: "Djerba", name: "Zarzis", country: "Tunisie" },
  { iata: "MIR", city: "Monastir", name: "Habib Bourguiba", country: "Tunisie" },
  { iata: "ALG", city: "Alger", name: "Houari Boumédiène", country: "Algérie" },
  { iata: "ORN", city: "Oran", name: "Ahmed Ben Bella", country: "Algérie" },
  { iata: "CZL", city: "Constantine", name: "Mohamed Boudiaf", country: "Algérie" },
  { iata: "CAI", city: "Le Caire", name: "Le Caire International", country: "Égypte" },
  { iata: "HRG", city: "Hurghada", name: "Hurghada", country: "Égypte" },
  { iata: "SSH", city: "Charm el-Cheikh", name: "Sharm El Sheikh", country: "Égypte" },
  { iata: "ALY", city: "Alexandrie", name: "El Nouzha", country: "Égypte" },
  { iata: "PTP", city: "Pointe-à-Pitre", name: "Pôle Caraïbes", country: "Guadeloupe" },
  { iata: "FDF", city: "Fort-de-France", name: "Aimé Césaire", country: "Martinique" },
  { iata: "DKR", city: "Dakar", name: "Blaise Diagne", country: "Sénégal" },
  { iata: "ABJ", city: "Abidjan", name: "Félix Houphouët-Boigny", country: "Côte d'Ivoire" },
  { iata: "ACC", city: "Accra", name: "Kotoka", country: "Ghana" },
  { iata: "LOS", city: "Lagos", name: "Murtala Muhammed", country: "Nigeria" },
  { iata: "ABV", city: "Abuja", name: "Nnamdi Azikiwe", country: "Nigeria" },
  { iata: "COO", city: "Cotonou", name: "Cadjehoun", country: "Bénin" },
  { iata: "LFW", city: "Lomé", name: "Gnassingbé Eyadéma", country: "Togo" },
  { iata: "OUA", city: "Ouagadougou", name: "Ouagadougou", country: "Burkina Faso" },
  { iata: "BKO", city: "Bamako", name: "Modibo Keïta", country: "Mali" },
  { iata: "NKC", city: "Nouakchott", name: "Oumtounsy", country: "Mauritanie" },
  { iata: "CKY", city: "Conakry", name: "Ahmed Sékou Touré", country: "Guinée" },
  { iata: "FNA", city: "Freetown", name: "Lungi", country: "Sierra Leone" },
  { iata: "ROB", city: "Monrovia", name: "Roberts", country: "Liberia" },
  { iata: "DLA", city: "Douala", name: "Douala", country: "Cameroun" },
  { iata: "YAO", city: "Yaoundé", name: "Nsimalen", country: "Cameroun" },
  { iata: "LBV", city: "Libreville", name: "Léon Mba", country: "Gabon" },
  { iata: "BGF", city: "Bangui", name: "M'Poko", country: "Centrafrique" },
  { iata: "NDJ", city: "N'Djamena", name: "Hassan Djamous", country: "Tchad" },
  { iata: "FIH", city: "Kinshasa", name: "N'djili", country: "RD Congo" },
  { iata: "BZV", city: "Brazzaville", name: "Maya-Maya", country: "Congo" },
  { iata: "PNR", city: "Pointe-Noire", name: "Agostinho-Neto", country: "Congo" },
  { iata: "LAD", city: "Luanda", name: "Quatro de Fevereiro", country: "Angola" },
  { iata: "NBO", city: "Nairobi", name: "Jomo Kenyatta", country: "Kenya" },
  { iata: "MBA", city: "Mombasa", name: "Moi", country: "Kenya" },
  { iata: "ADD", city: "Addis-Abeba", name: "Bole", country: "Éthiopie" },
  { iata: "DAR", city: "Dar es Salaam", name: "Julius Nyerere", country: "Tanzanie" },
  { iata: "JRO", city: "Kilimandjaro", name: "Kilimanjaro", country: "Tanzanie" },
  { iata: "EBB", city: "Entebbe", name: "Entebbe", country: "Ouganda" },
  { iata: "KGL", city: "Kigali", name: "Kigali International", country: "Rwanda" },
  { iata: "BJM", city: "Bujumbura", name: "Bujumbura", country: "Burundi" },
  { iata: "JNB", city: "Johannesburg", name: "O.R. Tambo", country: "Afrique du Sud" },
  { iata: "CPT", city: "Le Cap", name: "Cape Town International", country: "Afrique du Sud" },
  { iata: "DUR", city: "Durban", name: "King Shaka", country: "Afrique du Sud" },
  { iata: "WDH", city: "Windhoek", name: "Hosea Kutako", country: "Namibie" },
  { iata: "GBE", city: "Gaborone", name: "Sir Seretse Khama", country: "Botswana" },
  { iata: "HRE", city: "Harare", name: "Robert Gabriel Mugabe", country: "Zimbabwe" },
  { iata: "LUN", city: "Lusaka", name: "Kenneth Kaunda", country: "Zambie" },
  { iata: "MPM", city: "Maputo", name: "Maputo", country: "Mozambique" },
  { iata: "TNR", city: "Antananarivo", name: "Ivato International", country: "Madagascar" },
  { iata: "NOS", city: "Nosy Be", name: "Fascene", country: "Madagascar" },
  { iata: "TMM", city: "Toamasina", name: "Toamasina (Tamatave)", country: "Madagascar" },
  { iata: "DIE", city: "Antsiranana", name: "Arrachart (Diego-Suarez)", country: "Madagascar" },
  { iata: "MJN", city: "Mahajanga", name: "Amborovy (Majunga)", country: "Madagascar" },
  { iata: "TLE", city: "Toliara", name: "Toliara (Tuléar)", country: "Madagascar" },
  { iata: "FTU", city: "Tôlanaro", name: "Marillac (Fort-Dauphin)", country: "Madagascar" },
  { iata: "MOQ", city: "Morondava", name: "Morondava", country: "Madagascar" },
  { iata: "SVB", city: "Sambava", name: "Sambava", country: "Madagascar" },
  { iata: "SMS", city: "Sainte-Marie", name: "Sainte-Marie (Nosy Boraha)", country: "Madagascar" },
  { iata: "WMN", city: "Maroantsetra", name: "Maroantsetra", country: "Madagascar" },
  { iata: "WFI", city: "Fianarantsoa", name: "Fianarantsoa", country: "Madagascar" },
  { iata: "ANM", city: "Antalaha", name: "Antsirabato", country: "Madagascar" },
  { iata: "ATJ", city: "Antsirabe", name: "Antsirabe", country: "Madagascar" },
  { iata: "IVA", city: "Ambanja", name: "Ampampamena", country: "Madagascar" },
  { iata: "AMB", city: "Ambilobe", name: "Ambilobe", country: "Madagascar" },
  { iata: "VOH", city: "Vohémar", name: "Vohémar", country: "Madagascar" },
  { iata: "MNJ", city: "Mananjary", name: "Mananjary", country: "Madagascar" },
  { iata: "WVK", city: "Manakara", name: "Manakara", country: "Madagascar" },
  { iata: "RVA", city: "Farafangana", name: "Farafangana", country: "Madagascar" },
  { iata: "VND", city: "Vangaindrano", name: "Vangaindrano", country: "Madagascar" },
  { iata: "IHO", city: "Ihosy", name: "Ihosy", country: "Madagascar" },
  { iata: "MXM", city: "Morombe", name: "Morombe", country: "Madagascar" },
  { iata: "MXT", city: "Maintirano", name: "Maintirano", country: "Madagascar" },
  { iata: "BPY", city: "Besalampy", name: "Besalampy", country: "Madagascar" },
  { iata: "HVA", city: "Analalava", name: "Analalava", country: "Madagascar" },
  { iata: "WAI", city: "Antsohihy", name: "Ambalabe", country: "Madagascar" },
  { iata: "WMA", city: "Mandritsara", name: "Mandritsara", country: "Madagascar" },
  { iata: "ZWA", city: "Andapa", name: "Andapa", country: "Madagascar" },
  { iata: "WMR", city: "Mananara Avaratra", name: "Mananara Nord", country: "Madagascar" },
  { iata: "ZVA", city: "Miandrivazo", name: "Miandrivazo", country: "Madagascar" },
  { iata: "WTS", city: "Tsiroanomandidy", name: "Tsiroanomandidy", country: "Madagascar" },
  { iata: "WAM", city: "Ambatondrazaka", name: "Ambatondrazaka", country: "Madagascar" },
  { iata: "AMY", city: "Ambatomainty", name: "Ambatomainty", country: "Madagascar" },
  { iata: "AMP", city: "Ampanihy", name: "Ampanihy", country: "Madagascar" },
  { iata: "DVD", city: "Andavadoaka", name: "Andavadoaka", country: "Madagascar" },
  { iata: "JVA", city: "Ankavandra", name: "Ankavandra", country: "Madagascar" },
  { iata: "WAK", city: "Ankazoabo", name: "Ankazoabo", country: "Madagascar" },
  { iata: "WAQ", city: "Antsalova", name: "Antsalova", country: "Madagascar" },
  { iata: "WBE", city: "Bealanana", name: "Ankaizina", country: "Madagascar" },
  { iata: "OVA", city: "Bekily", name: "Bekily", country: "Madagascar" },
  { iata: "BMD", city: "Belo sur Tsiribihina", name: "Belo sur Tsiribihina", country: "Madagascar" },
  { iata: "WBD", city: "Befandriana", name: "Befandriana-Avaratra", country: "Madagascar" },
  { iata: "WBO", city: "Beroroha", name: "Antsoa", country: "Madagascar" },
  { iata: "BKU", city: "Betioky", name: "Betioky", country: "Madagascar" },
  { iata: "WPB", city: "Boriziny", name: "Port Bergé", country: "Madagascar" },
  { iata: "DOA", city: "Doany", name: "Doany", country: "Madagascar" },
  { iata: "ILK", city: "Ilaka Atsinanana", name: "Ilaka Atsinanana", country: "Madagascar" },
  { iata: "VVB", city: "Mahanoro", name: "Mahanoro", country: "Madagascar" },
  { iata: "WML", city: "Malaimbandy", name: "Malaimbandy", country: "Madagascar" },
  { iata: "WMP", city: "Mampikony", name: "Mampikony", country: "Madagascar" },
  { iata: "WMD", city: "Mandabe", name: "Mandabe", country: "Madagascar" },
  { iata: "MJA", city: "Manja", name: "Manja", country: "Madagascar" },
  { iata: "TVA", city: "Morafenobe", name: "Morafenobe", country: "Madagascar" },
  { iata: "DWB", city: "Soalala", name: "Soalala", country: "Madagascar" },
  { iata: "WTA", city: "Tambohorano", name: "Tambohorano", country: "Madagascar" },
  { iata: "TDV", city: "Tanandava", name: "Samangoky", country: "Madagascar" },
  { iata: "TTS", city: "Tsaratanana", name: "Tsaratanana", country: "Madagascar" },
  { iata: "VAT", city: "Vatomandry", name: "Vatomandry", country: "Madagascar" },
  { iata: "MRU", city: "Port-Louis", name: "Sir Seewoosagur Ramgoolam", country: "Maurice" },
  { iata: "SEZ", city: "Mahé", name: "Seychelles", country: "Seychelles" },
  { iata: "RUN", city: "Saint-Denis", name: "Roland Garros", country: "La Réunion" },
  { iata: "DZA", city: "Dzaoudzi", name: "Pamandzi", country: "Mayotte" },
  { iata: "DXB", city: "Dubaï", name: "Dubaï International", country: "Émirats arabes unis" },
  { iata: "DWC", city: "Dubaï", name: "Al Maktoum", country: "Émirats arabes unis" },
  { iata: "AUH", city: "Abou Dabi", name: "Zayed International", country: "Émirats arabes unis" },
  { iata: "SHJ", city: "Charjah", name: "Sharjah", country: "Émirats arabes unis" },
  { iata: "DOH", city: "Doha", name: "Hamad International", country: "Qatar" },
  { iata: "RUH", city: "Riyad", name: "King Khalid", country: "Arabie saoudite" },
  { iata: "JED", city: "Djeddah", name: "King Abdulaziz", country: "Arabie saoudite" },
  { iata: "MED", city: "Médine", name: "Prince Mohammad Bin Abdulaziz", country: "Arabie saoudite" },
  { iata: "MCT", city: "Mascate", name: "Muscat", country: "Oman" },
  { iata: "BAH", city: "Manama", name: "Bahreïn", country: "Bahreïn" },
  { iata: "KWI", city: "Koweït", name: "Kuwait International", country: "Koweït" },
  { iata: "AMM", city: "Amman", name: "Queen Alia", country: "Jordanie" },
  { iata: "BEY", city: "Beyrouth", name: "Rafic Hariri", country: "Liban" },
  { iata: "TLV", city: "Tel Aviv", name: "Ben Gourion", country: "Israël" },
  { iata: "BGW", city: "Bagdad", name: "Baghdad", country: "Irak" },
  { iata: "EBL", city: "Erbil", name: "Erbil", country: "Irak" },
  { iata: "THR", city: "Téhéran", name: "Mehrabad", country: "Iran" },
  { iata: "IKA", city: "Téhéran", name: "Imam Khomeini", country: "Iran" },
  { iata: "NRT", city: "Tokyo", name: "Narita", country: "Japon" },
  { iata: "HND", city: "Tokyo", name: "Haneda", country: "Japon" },
  { iata: "KIX", city: "Osaka", name: "Kansai", country: "Japon" },
  { iata: "ITM", city: "Osaka", name: "Itami", country: "Japon" },
  { iata: "NGO", city: "Nagoya", name: "Chubu Centrair", country: "Japon" },
  { iata: "FUK", city: "Fukuoka", name: "Fukuoka", country: "Japon" },
  { iata: "CTS", city: "Sapporo", name: "New Chitose", country: "Japon" },
  { iata: "ICN", city: "Séoul", name: "Incheon", country: "Corée du Sud" },
  { iata: "GMP", city: "Séoul", name: "Gimpo", country: "Corée du Sud" },
  { iata: "PUS", city: "Busan", name: "Gimhae", country: "Corée du Sud" },
  { iata: "PEK", city: "Pékin", name: "Capitale", country: "Chine" },
  { iata: "PKX", city: "Pékin", name: "Daxing", country: "Chine" },
  { iata: "PVG", city: "Shanghai", name: "Pudong", country: "Chine" },
  { iata: "SHA", city: "Shanghai", name: "Hongqiao", country: "Chine" },
  { iata: "CAN", city: "Canton", name: "Baiyun", country: "Chine" },
  { iata: "SZX", city: "Shenzhen", name: "Bao'an", country: "Chine" },
  { iata: "CTU", city: "Chengdu", name: "Shuangliu", country: "Chine" },
  { iata: "TFU", city: "Chengdu", name: "Tianfu", country: "Chine" },
  { iata: "HGH", city: "Hangzhou", name: "Xiaoshan", country: "Chine" },
  { iata: "XIY", city: "Xi'an", name: "Xianyang", country: "Chine" },
  { iata: "CKG", city: "Chongqing", name: "Jiangbei", country: "Chine" },
  { iata: "HKG", city: "Hong Kong", name: "Chek Lap Kok", country: "Hong Kong" },
  { iata: "MFM", city: "Macao", name: "Macao", country: "Macao" },
  { iata: "TPE", city: "Taipei", name: "Taoyuan", country: "Taïwan" },
  { iata: "TSA", city: "Taipei", name: "Songshan", country: "Taïwan" },
  { iata: "MNL", city: "Manille", name: "Ninoy Aquino", country: "Philippines" },
  { iata: "CEB", city: "Cebu", name: "Mactan-Cebu", country: "Philippines" },
  { iata: "CGK", city: "Jakarta", name: "Soekarno-Hatta", country: "Indonésie" },
  { iata: "DPS", city: "Denpasar", name: "Ngurah Rai Bali", country: "Indonésie" },
  { iata: "SUB", city: "Surabaya", name: "Juanda", country: "Indonésie" },
  { iata: "KUL", city: "Kuala Lumpur", name: "Kuala Lumpur International", country: "Malaisie" },
  { iata: "SZB", city: "Kuala Lumpur", name: "Sultan Abdul Aziz Shah", country: "Malaisie" },
  { iata: "PEN", city: "Penang", name: "Penang", country: "Malaisie" },
  { iata: "SIN", city: "Singapour", name: "Changi", country: "Singapour" },
  { iata: "BKK", city: "Bangkok", name: "Suvarnabhumi", country: "Thaïlande" },
  { iata: "DMK", city: "Bangkok", name: "Don Mueang", country: "Thaïlande" },
  { iata: "HKT", city: "Phuket", name: "Phuket", country: "Thaïlande" },
  { iata: "CNX", city: "Chiang Mai", name: "Chiang Mai", country: "Thaïlande" },
  { iata: "SGN", city: "Hô Chi Minh-Ville", name: "Tân Sơn Nhất", country: "Viêt Nam" },
  { iata: "HAN", city: "Hanoï", name: "Nội Bài", country: "Viêt Nam" },
  { iata: "DAD", city: "Đà Nẵng", name: "Đà Nẵng", country: "Viêt Nam" },
  { iata: "PNH", city: "Phnom Penh", name: "Phnom Penh", country: "Cambodge" },
  { iata: "REP", city: "Siem Reap", name: "Angkor", country: "Cambodge" },
  { iata: "VTE", city: "Vientiane", name: "Wattay", country: "Laos" },
  { iata: "RGN", city: "Yangon", name: "Yangon", country: "Myanmar" },
  { iata: "DEL", city: "Delhi", name: "Indira Gandhi", country: "Inde" },
  { iata: "BOM", city: "Mumbai", name: "Chhatrapati Shivaji", country: "Inde" },
  { iata: "BLR", city: "Bengaluru", name: "Kempegowda", country: "Inde" },
  { iata: "MAA", city: "Chennai", name: "Chennai", country: "Inde" },
  { iata: "HYD", city: "Hyderabad", name: "Rajiv Gandhi", country: "Inde" },
  { iata: "CCU", city: "Kolkata", name: "Netaji Subhas Chandra Bose", country: "Inde" },
  { iata: "GOI", city: "Goa", name: "Dabolim", country: "Inde" },
  { iata: "COK", city: "Kochi", name: "Cochin", country: "Inde" },
  { iata: "CMB", city: "Colombo", name: "Bandaranaike", country: "Sri Lanka" },
  { iata: "DAC", city: "Dacca", name: "Hazrat Shahjalal", country: "Bangladesh" },
  { iata: "KTM", city: "Katmandou", name: "Tribhuvan", country: "Népal" },
  { iata: "ISB", city: "Islamabad", name: "Islamabad International", country: "Pakistan" },
  { iata: "KHI", city: "Karachi", name: "Jinnah", country: "Pakistan" },
  { iata: "LHE", city: "Lahore", name: "Allama Iqbal", country: "Pakistan" },
  { iata: "KBL", city: "Kaboul", name: "Hamid Karzai", country: "Afghanistan" },
  { iata: "TAS", city: "Tachkent", name: "Islam Karimov", country: "Ouzbékistan" },
  { iata: "ALA", city: "Almaty", name: "Almaty", country: "Kazakhstan" },
  { iata: "NQZ", city: "Astana", name: "Noursoultan Nazarbaïev", country: "Kazakhstan" },
  { iata: "FRU", city: "Bichkek", name: "Manas", country: "Kirghizistan" },
  { iata: "ULN", city: "Oulan-Bator", name: "Chinggis Khaan", country: "Mongolie" },
  { iata: "SYD", city: "Sydney", name: "Kingsford Smith", country: "Australie" },
  { iata: "MEL", city: "Melbourne", name: "Tullamarine", country: "Australie" },
  { iata: "BNE", city: "Brisbane", name: "Brisbane", country: "Australie" },
  { iata: "PER", city: "Perth", name: "Perth", country: "Australie" },
  { iata: "ADL", city: "Adélaïde", name: "Adelaide", country: "Australie" },
  { iata: "CNS", city: "Cairns", name: "Cairns", country: "Australie" },
  { iata: "AKL", city: "Auckland", name: "Auckland", country: "Nouvelle-Zélande" },
  { iata: "WLG", city: "Wellington", name: "Wellington", country: "Nouvelle-Zélande" },
  { iata: "CHC", city: "Christchurch", name: "Christchurch", country: "Nouvelle-Zélande" },
  { iata: "NAN", city: "Nadi", name: "Nadi", country: "Fidji" },
  { iata: "PPT", city: "Papeete", name: "Faa'a", country: "Polynésie française" },
  { iata: "NOU", city: "Nouméa", name: "La Tontouta", country: "Nouvelle-Calédonie" },
  { iata: "GUM", city: "Guam", name: "Antonio B. Won Pat", country: "Guam" },
  { iata: "MLA", city: "La Valette", name: "Malte International", country: "Malte" },
  { iata: "LCA", city: "Larnaca", name: "Larnaca", country: "Chypre" },
  { iata: "PFO", city: "Paphos", name: "Paphos", country: "Chypre" },
  { iata: "BTS", city: "Bratislava", name: "M. R. Štefánik", country: "Slovaquie" },
  { iata: "KSC", city: "Košice", name: "Košice", country: "Slovaquie" },
  { iata: "SJJ", city: "Sarajevo", name: "Sarajevo", country: "Bosnie-Herzégovine" },
  { iata: "TGD", city: "Podgorica", name: "Podgorica", country: "Monténégro" },
  { iata: "TIV", city: "Tivat", name: "Tivat", country: "Monténégro" },
  { iata: "PRN", city: "Pristina", name: "Adem Jashari", country: "Kosovo" },
  { iata: "RMO", city: "Chișinău", name: "Chișinău", country: "Moldavie" },
  { iata: "GIB", city: "Gibraltar", name: "Gibraltar", country: "Gibraltar" },
  { iata: "JER", city: "Jersey", name: "Jersey", country: "Jersey" },
  { iata: "GCI", city: "Guernesey", name: "Guernsey", country: "Guernesey" },
  { iata: "IOM", city: "Douglas", name: "Isle of Man", country: "Île de Man" },
  { iata: "INV", city: "Inverness", name: "Inverness", country: "Royaume-Uni" },
  { iata: "CWL", city: "Cardiff", name: "Cardiff", country: "Royaume-Uni" },
  { iata: "BFS", city: "Belfast", name: "Belfast International", country: "Royaume-Uni" },
  { iata: "BLL", city: "Billund", name: "Billund", country: "Danemark" },
  { iata: "AAL", city: "Aalborg", name: "Aalborg", country: "Danemark" },
  { iata: "TOS", city: "Tromsø", name: "Tromsø", country: "Norvège" },
  { iata: "SVG", city: "Stavanger", name: "Sola", country: "Norvège" },
  { iata: "TRD", city: "Trondheim", name: "Værnes", country: "Norvège" },
  { iata: "MMX", city: "Malmö", name: "Sturup", country: "Suède" },
  { iata: "TKU", city: "Turku", name: "Turku", country: "Finlande" },
  { iata: "OUL", city: "Oulu", name: "Oulu", country: "Finlande" },
  { iata: "GDN", city: "Gdańsk", name: "Lech Wałęsa", country: "Pologne" },
  { iata: "WRO", city: "Wrocław", name: "Copernicus", country: "Pologne" },
  { iata: "KTW", city: "Katowice", name: "Pyrzowice", country: "Pologne" },
  { iata: "CLJ", city: "Cluj-Napoca", name: "Avram Iancu", country: "Roumanie" },
  { iata: "IAS", city: "Iași", name: "Iași", country: "Roumanie" },
  { iata: "VAR", city: "Varna", name: "Varna", country: "Bulgarie" },
  { iata: "BOJ", city: "Bourgas", name: "Burgas", country: "Bulgarie" },
  { iata: "INI", city: "Niš", name: "Constantin le Grand", country: "Serbie" },
  { iata: "OHD", city: "Ohrid", name: "Saint-Paul-l'Apôtre", country: "Macédoine du Nord" },
  { iata: "KIV", city: "Chișinău", name: "Chișinău", country: "Moldavie" },
  { iata: "ODS", city: "Odessa", name: "Odessa", country: "Ukraine" },
  { iata: "LWO", city: "Lviv", name: "Lviv", country: "Ukraine" },
  { iata: "IEV", city: "Kyiv", name: "Zhuliany", country: "Ukraine" },
  { iata: "BUS", city: "Batoumi", name: "Batoumi", country: "Géorgie" },
  { iata: "BJL", city: "Banjul", name: "Banjul International", country: "Gambie" },
  { iata: "OXB", city: "Bissau", name: "Osvaldo Vieira", country: "Guinée-Bissau" },
  { iata: "RAI", city: "Praia", name: "Nelson Mandela", country: "Cap-Vert" },
  { iata: "SID", city: "Sal", name: "Amílcar Cabral", country: "Cap-Vert" },
  { iata: "VXE", city: "São Vicente", name: "Cesária Évora", country: "Cap-Vert" },
  { iata: "SSG", city: "Malabo", name: "Malabo", country: "Guinée équatoriale" },
  { iata: "TMS", city: "São Tomé", name: "São Tomé", country: "Sao Tomé-et-Principe" },
  { iata: "NIM", city: "Niamey", name: "Diori Hamani", country: "Niger" },
  { iata: "JUB", city: "Djouba", name: "Juba", country: "Soudan du Sud" },
  { iata: "KRT", city: "Khartoum", name: "Khartoum", country: "Soudan" },
  { iata: "ASM", city: "Asmara", name: "Asmara", country: "Érythrée" },
  { iata: "JIB", city: "Djibouti", name: "Ambouli", country: "Djibouti" },
  { iata: "MGQ", city: "Mogadiscio", name: "Aden Adde", country: "Somalie" },
  { iata: "HGA", city: "Hargeisa", name: "Egal", country: "Somaliland" },
  { iata: "LLW", city: "Lilongwe", name: "Kamuzu", country: "Malawi" },
  { iata: "BLZ", city: "Blantyre", name: "Chileka", country: "Malawi" },
  { iata: "MSU", city: "Maseru", name: "Moshoeshoe I", country: "Lesotho" },
  { iata: "SHO", city: "Manzini", name: "King Mswati III", country: "Eswatini" },
  { iata: "HAH", city: "Moroni", name: "Prince Saïd Ibrahim", country: "Comores" },
  { iata: "AJN", city: "Anjouan", name: "Ouani", country: "Comores" },
  { iata: "MJI", city: "Tripoli", name: "Mitiga", country: "Libye" },
  { iata: "TIP", city: "Tripoli", name: "Tripoli International", country: "Libye" },
  { iata: "BEN", city: "Benghazi", name: "Benina", country: "Libye" },
  { iata: "HBE", city: "Alexandrie", name: "Borg El Arab", country: "Égypte" },
  { iata: "LXR", city: "Louxor", name: "Louxor", country: "Égypte" },
  { iata: "ASW", city: "Assouan", name: "Assouan", country: "Égypte" },
  { iata: "KIS", city: "Kisumu", name: "Kisumu", country: "Kenya" },
  { iata: "ZNZ", city: "Zanzibar", name: "Abeid Amani Karume", country: "Tanzanie" },
  { iata: "MWZ", city: "Mwanza", name: "Mwanza", country: "Tanzanie" },
  { iata: "VFA", city: "Victoria Falls", name: "Victoria Falls", country: "Zimbabwe" },
  { iata: "LVI", city: "Livingstone", name: "Harry Mwanga Nkumbula", country: "Zambie" },
  { iata: "BEW", city: "Beira", name: "Beira", country: "Mozambique" },
  { iata: "RRG", city: "Rodrigues", name: "Plaine Corail", country: "Maurice" },
  { iata: "PRI", city: "Praslin", name: "Praslin", country: "Seychelles" },
  { iata: "PHC", city: "Port Harcourt", name: "Port Harcourt", country: "Nigeria" },
  { iata: "KAN", city: "Kano", name: "Mallam Aminu", country: "Nigeria" },
  { iata: "BJV", city: "Bodrum", name: "Milas-Bodrum", country: "Turquie" },
  { iata: "ESB", city: "Ankara", name: "Esenboğa", country: "Turquie" },
  { iata: "TZX", city: "Trabzon", name: "Trabzon", country: "Turquie" },
  { iata: "ADA", city: "Adana", name: "Şakirpaşa", country: "Turquie" },
  { iata: "DAM", city: "Damas", name: "Damas", country: "Syrie" },
  { iata: "ALP", city: "Alep", name: "Alep", country: "Syrie" },
  { iata: "SAH", city: "Sanaa", name: "Sanaa International", country: "Yémen" },
  { iata: "ADE", city: "Aden", name: "Aden International", country: "Yémen" },
  { iata: "MLE", city: "Malé", name: "Velana", country: "Maldives" },
  { iata: "GAN", city: "Addu", name: "Gan", country: "Maldives" },
  { iata: "PBH", city: "Paro", name: "Paro", country: "Bhoutan" },
  { iata: "FNJ", city: "Pyongyang", name: "Sunan", country: "Corée du Nord" },
  { iata: "DYU", city: "Douchanbé", name: "Douchanbé", country: "Tadjikistan" },
  { iata: "ASB", city: "Achgabat", name: "Achgabat", country: "Turkménistan" },
  { iata: "CIT", city: "Chimkent", name: "Chimkent", country: "Kazakhstan" },
  { iata: "OSS", city: "Och", name: "Och", country: "Kirghizistan" },
  { iata: "BWN", city: "Bandar Seri Begawan", name: "Brunei International", country: "Brunei" },
  { iata: "DIL", city: "Dili", name: "Presidente Nicolau Lobato", country: "Timor oriental" },
  { iata: "CRK", city: "Manille", name: "Clark", country: "Philippines" },
  { iata: "DVO", city: "Davao", name: "Francisco Bangoy", country: "Philippines" },
  { iata: "KLO", city: "Kalibo", name: "Kalibo", country: "Philippines" },
  { iata: "JOG", city: "Yogyakarta", name: "Yogyakarta International", country: "Indonésie" },
  { iata: "UPG", city: "Makassar", name: "Sultan Hasanuddin", country: "Indonésie" },
  { iata: "LOP", city: "Lombok", name: "Zainuddin Abdul Madjid", country: "Indonésie" },
  { iata: "BKI", city: "Kota Kinabalu", name: "Kota Kinabalu", country: "Malaisie" },
  { iata: "KCH", city: "Kuching", name: "Kuching", country: "Malaisie" },
  { iata: "USM", city: "Koh Samui", name: "Samui", country: "Thaïlande" },
  { iata: "UTP", city: "Pattaya", name: "U-Tapao", country: "Thaïlande" },
  { iata: "CXR", city: "Nha Trang", name: "Cam Ranh", country: "Viêt Nam" },
  { iata: "HPH", city: "Haïphong", name: "Cát Bi", country: "Viêt Nam" },
  { iata: "MDL", city: "Mandalay", name: "Mandalay", country: "Myanmar" },
  { iata: "AMD", city: "Ahmedabad", name: "Sardar Vallabhbhai Patel", country: "Inde" },
  { iata: "PNQ", city: "Pune", name: "Pune", country: "Inde" },
  { iata: "JAI", city: "Jaipur", name: "Jaipur", country: "Inde" },
  { iata: "TRV", city: "Thiruvananthapuram", name: "Trivandrum", country: "Inde" },
  { iata: "ATQ", city: "Amritsar", name: "Sri Guru Ram Dass Jee", country: "Inde" },
  { iata: "IXB", city: "Bagdogra", name: "Bagdogra", country: "Inde" },
  { iata: "CGP", city: "Chittagong", name: "Shah Amanat", country: "Bangladesh" },
  { iata: "PKR", city: "Pokhara", name: "Pokhara", country: "Népal" },
  { iata: "PEW", city: "Peshawar", name: "Bacha Khan", country: "Pakistan" },
  { iata: "SKT", city: "Sialkot", name: "Sialkot", country: "Pakistan" },
  { iata: "GUA", city: "Guatemala", name: "La Aurora", country: "Guatemala" },
  { iata: "FRS", city: "Flores", name: "Mundo Maya", country: "Guatemala" },
  { iata: "SAL", city: "San Salvador", name: "Óscar Arnulfo Romero", country: "Salvador" },
  { iata: "TGU", city: "Tegucigalpa", name: "Toncontín", country: "Honduras" },
  { iata: "XPL", city: "Comayagua", name: "Palmerola", country: "Honduras" },
  { iata: "SAP", city: "San Pedro Sula", name: "Ramón Villeda Morales", country: "Honduras" },
  { iata: "MGA", city: "Managua", name: "Augusto C. Sandino", country: "Nicaragua" },
  { iata: "BZE", city: "Belize City", name: "Philip S. W. Goldson", country: "Belize" },
  { iata: "PAP", city: "Port-au-Prince", name: "Toussaint Louverture", country: "Haïti" },
  { iata: "CAP", city: "Cap-Haïtien", name: "Cap-Haïtien", country: "Haïti" },
  { iata: "KIN", city: "Kingston", name: "Norman Manley", country: "Jamaïque" },
  { iata: "POS", city: "Port-d'Espagne", name: "Piarco", country: "Trinité-et-Tobago" },
  { iata: "TAB", city: "Tobago", name: "A. N. R. Robinson", country: "Trinité-et-Tobago" },
  { iata: "BGI", city: "Bridgetown", name: "Grantley Adams", country: "Barbade" },
  { iata: "UVF", city: "Vieux Fort", name: "Hewanorra", country: "Sainte-Lucie" },
  { iata: "SLU", city: "Castries", name: "George F. L. Charles", country: "Sainte-Lucie" },
  { iata: "ANU", city: "Saint John's", name: "V. C. Bird", country: "Antigua-et-Barbuda" },
  { iata: "GND", city: "Saint-Georges", name: "Maurice Bishop", country: "Grenade" },
  { iata: "SVD", city: "Kingstown", name: "Argyle", country: "Saint-Vincent-et-les-Grenadines" },
  { iata: "SKB", city: "Basseterre", name: "Robert L. Bradshaw", country: "Saint-Kitts-et-Nevis" },
  { iata: "DOM", city: "Roseau", name: "Douglas-Charles", country: "Dominique" },
  { iata: "SXM", city: "Philipsburg", name: "Princess Juliana", country: "Saint-Martin" },
  { iata: "SFG", city: "Grand-Case", name: "L'Espérance", country: "Saint-Martin" },
  { iata: "AUA", city: "Oranjestad", name: "Queen Beatrix", country: "Aruba" },
  { iata: "CUR", city: "Willemstad", name: "Curaçao", country: "Curaçao" },
  { iata: "BON", city: "Kralendijk", name: "Flamingo", country: "Bonaire" },
  { iata: "PLS", city: "Providenciales", name: "Providenciales", country: "Îles Turques-et-Caïques" },
  { iata: "GCM", city: "Grand Cayman", name: "Owen Roberts", country: "Îles Caïmans" },
  { iata: "BDA", city: "Hamilton", name: "L.F. Wade", country: "Bermudes" },
  { iata: "SJU", city: "San Juan", name: "Luis Muñoz Marín", country: "Porto Rico" },
  { iata: "STT", city: "Charlotte Amalie", name: "Cyril E. King", country: "Îles Vierges américaines" },
  { iata: "PBM", city: "Paramaribo", name: "Johan Adolf Pengel", country: "Suriname" },
  { iata: "GEO", city: "Georgetown", name: "Cheddi Jagan", country: "Guyana" },
  { iata: "CAY", city: "Cayenne", name: "Félix Eboué", country: "Guyane" },
  { iata: "FSP", city: "Saint-Pierre", name: "Saint-Pierre", country: "Saint-Pierre-et-Miquelon" },
  { iata: "VCP", city: "Campinas", name: "Viracopos", country: "Brésil" },
  { iata: "CNF", city: "Belo Horizonte", name: "Confins", country: "Brésil" },
  { iata: "REC", city: "Recife", name: "Guararapes", country: "Brésil" },
  { iata: "FOR", city: "Fortaleza", name: "Pinto Martins", country: "Brésil" },
  { iata: "POA", city: "Porto Alegre", name: "Salgado Filho", country: "Brésil" },
  { iata: "BEL", city: "Belém", name: "Val de Cans", country: "Brésil" },
  { iata: "MAO", city: "Manaus", name: "Eduardo Gomes", country: "Brésil" },
  { iata: "CUE", city: "Cuenca", name: "Mariscal Lamar", country: "Équateur" },
  { iata: "GYE", city: "Guayaquil", name: "José Joaquín de Olmedo", country: "Équateur" },
  { iata: "CLO", city: "Cali", name: "Alfonso Bonilla Aragón", country: "Colombie" },
  { iata: "CTG", city: "Carthagène", name: "Rafael Núñez", country: "Colombie" },
  { iata: "CUZ", city: "Cusco", name: "Alejandro Velasco Astete", country: "Pérou" },
  { iata: "AQP", city: "Arequipa", name: "Rodríguez Ballón", country: "Pérou" },
  { iata: "VVI", city: "Santa Cruz", name: "Viru Viru", country: "Bolivie" },
  { iata: "IQQ", city: "Iquique", name: "Diego Aracena", country: "Chili" },
  { iata: "ANF", city: "Antofagasta", name: "Andrés Sabella", country: "Chili" },
  { iata: "COR", city: "Córdoba", name: "Ingeniero Ambrosio Taravella", country: "Argentine" },
  { iata: "MDZ", city: "Mendoza", name: "El Plumerillo", country: "Argentine" },
  { iata: "BRC", city: "Bariloche", name: "Teniente Luis Candelaria", country: "Argentine" },
  { iata: "POM", city: "Port Moresby", name: "Jackson", country: "Papouasie-Nouvelle-Guinée" },
  { iata: "HIR", city: "Honiara", name: "Honiara", country: "Îles Salomon" },
  { iata: "VLI", city: "Port-Vila", name: "Bauerfield", country: "Vanuatu" },
  { iata: "APW", city: "Apia", name: "Faleolo", country: "Samoa" },
  { iata: "TBU", city: "Nuku'alofa", name: "Fua'amotu", country: "Tonga" },
  { iata: "ROR", city: "Koror", name: "Roman Tmetuchl", country: "Palaos" },
  { iata: "MAJ", city: "Majuro", name: "Amata Kabua", country: "Îles Marshall" },
  { iata: "PNI", city: "Pohnpei", name: "Pohnpei", country: "Micronésie" },
  { iata: "TRW", city: "Tarawa", name: "Bonriki", country: "Kiribati" },
  { iata: "FUN", city: "Funafuti", name: "Funafuti", country: "Tuvalu" },
  { iata: "INU", city: "Yaren", name: "Nauru", country: "Nauru" },
  { iata: "RAR", city: "Rarotonga", name: "Rarotonga", country: "Îles Cook" },
  { iata: "SUV", city: "Suva", name: "Nausori", country: "Fidji" },
  { iata: "CHT", city: "Chatham", name: "Tuuta", country: "Nouvelle-Zélande" },
  { iata: "ZQN", city: "Queenstown", name: "Queenstown", country: "Nouvelle-Zélande" },
  { iata: "OOL", city: "Gold Coast", name: "Gold Coast", country: "Australie" },
  { iata: "DRW", city: "Darwin", name: "Darwin", country: "Australie" },
  { iata: "HBA", city: "Hobart", name: "Hobart", country: "Australie" },
  { iata: "SPN", city: "Saipan", name: "Saipan", country: "Mariannes du Nord" },
  { iata: "PPG", city: "Pago Pago", name: "Pago Pago", country: "Samoa américaines" },
  { iata: "WLS", city: "Wallis", name: "Hihifo", country: "Wallis-et-Futuna" },
  { iata: "FUT", city: "Futuna", name: "Pointe Vele", country: "Wallis-et-Futuna" },
];

const unique = new Map<string, Airport>();
for (const airport of AIRPORTS) unique.set(airport.iata, airport);
export const AIRPORT_INDEX = unique;

export function getAirport(iata: string) {
  return AIRPORT_INDEX.get(iata.trim().toUpperCase());
}

export function formatAirportLabel(airport: Airport) {
  return `${airport.city} — ${airport.name} (${airport.iata})`;
}

export function searchAirports(query: string, limit = 16): Airport[] {
  const q = query.trim().toLowerCase().replace(/[—–]/g, " ");
  if (!q) {
    return POPULAR_IATA.map((code) => AIRPORT_INDEX.get(code)).filter(Boolean) as Airport[];
  }
  const scored = [...AIRPORT_INDEX.values()]
    .map((airport) => {
      const iata = airport.iata.toLowerCase();
      const city = airport.city.toLowerCase();
      const name = airport.name.toLowerCase();
      const country = airport.country.toLowerCase();
      let score = 0;
      if (iata === q) score = 100;
      else if (iata.startsWith(q)) score = 80;
      else if (city.startsWith(q)) score = 70;
      else if (country === q || country.startsWith(q)) score = 65;
      else if (name.startsWith(q)) score = 60;
      else if (city.includes(q) || name.includes(q) || country.includes(q) || iata.includes(q)) score = 30;
      return { airport, score };
    })
    .filter((row) => row.score > 0)
    .sort((a, b) => b.score - a.score || a.airport.city.localeCompare(b.airport.city));
  const countryHits = scored.filter((row) => row.airport.country.toLowerCase() === q || row.airport.country.toLowerCase().startsWith(q));
  const cap = countryHits.length > limit ? Math.min(countryHits.length, 60) : limit;
  return scored.slice(0, cap).map((row) => row.airport);
}
