import type { Airport } from "./types";

export const POPULAR_IATA = [
  "CDG",
  "ORY",
  "LHR",
  "AMS",
  "JFK",
  "LAX",
  "DXB",
  "SIN",
  "HND",
  "MAD",
  "FCO",
  "IST",
];

export const AIRPORTS: Airport[] = [
  { iata: "CDG", city: "Paris", name: "Charles de Gaulle", country: "France" },
  { iata: "ORY", city: "Paris", name: "Orly", country: "France" },
  { iata: "BVA", city: "Paris", name: "Beauvais-Tillé", country: "France" },
  { iata: "LYS", city: "Lyon", name: "Saint-Exupéry", country: "France" },
  { iata: "MRS", city: "Marseille", name: "Provence", country: "France" },
  { iata: "NCE", city: "Nice", name: "Côte d'Azur", country: "France" },
  { iata: "TLS", city: "Toulouse", name: "Blagnac", country: "France" },
  { iata: "NTE", city: "Nantes", name: "Atlantique", country: "France" },
  { iata: "BOD", city: "Bordeaux", name: "Mérignac", country: "France" },
  { iata: "LIL", city: "Lille", name: "Lesquin", country: "France" },
  { iata: "SXB", city: "Strasbourg", name: "Entzheim", country: "France" },
  { iata: "MPL", city: "Montpellier", name: "Méditerranée", country: "France" },
  { iata: "NTE", city: "Nantes", name: "Atlantique", country: "France" },
  { iata: "RNS", city: "Rennes", name: "Saint-Jacques", country: "France" },
  { iata: "BIQ", city: "Biarritz", name: "Pays Basque", country: "France" },
  { iata: "PGF", city: "Perpignan", name: "Rivesaltes", country: "France" },
  { iata: "AJA", city: "Ajaccio", name: "Napoléon Bonaparte", country: "France" },
  { iata: "BIA", city: "Bastia", name: "Poretta", country: "France" },
  { iata: "FSC", city: "Figari", name: "Sud Corse", country: "France" },
  { iata: "CFR", city: "Caen", name: "Carpiquet", country: "France" },
  { iata: "LHR", city: "Londres", name: "Heathrow", country: "Royaume-Uni" },
  { iata: "LGW", city: "Londres", name: "Gatwick", country: "Royaume-Uni" },
  { iata: "STN", city: "Londres", name: "Stansted", country: "Royaume-Uni" },
  { iata: "LTN", city: "Londres", name: "Luton", country: "Royaume-Uni" },
  { iata: "LCY", city: "Londres", name: "City", country: "Royaume-Uni" },
  { iata: "MAN", city: "Manchester", name: "Manchester", country: "Royaume-Uni" },
  { iata: "EDI", city: "Édimbourg", name: "Edinburgh", country: "Royaume-Uni" },
  { iata: "BHX", city: "Birmingham", name: "Birmingham", country: "Royaume-Uni" },
  { iata: "GLA", city: "Glasgow", name: "Glasgow", country: "Royaume-Uni" },
  { iata: "DUB", city: "Dublin", name: "Dublin", country: "Irlande" },
  { iata: "SNN", city: "Shannon", name: "Shannon", country: "Irlande" },
  { iata: "AMS", city: "Amsterdam", name: "Schiphol", country: "Pays-Bas" },
  { iata: "RTM", city: "Rotterdam", name: "The Hague", country: "Pays-Bas" },
  { iata: "BRU", city: "Bruxelles", name: "Zaventem", country: "Belgique" },
  { iata: "CRL", city: "Charleroi", name: "Bruxelles-Sud", country: "Belgique" },
  { iata: "LUX", city: "Luxembourg", name: "Findel", country: "Luxembourg" },
  { iata: "FRA", city: "Francfort", name: "Francfort", country: "Allemagne" },
  { iata: "MUC", city: "Munich", name: "Franz Josef Strauss", country: "Allemagne" },
  { iata: "BER", city: "Berlin", name: "Brandebourg", country: "Allemagne" },
  { iata: "DUS", city: "Düsseldorf", name: "Düsseldorf", country: "Allemagne" },
  { iata: "HAM", city: "Hambourg", name: "Hambourg", country: "Allemagne" },
  { iata: "CGN", city: "Cologne", name: "Bonn", country: "Allemagne" },
  { iata: "STR", city: "Stuttgart", name: "Stuttgart", country: "Allemagne" },
  { iata: "MAD", city: "Madrid", name: "Adolfo Suárez Barajas", country: "Espagne" },
  { iata: "BCN", city: "Barcelone", name: "Josep Tarradellas El Prat", country: "Espagne" },
  { iata: "AGP", city: "Malaga", name: "Costa del Sol", country: "Espagne" },
  { iata: "PMI", city: "Palma", name: "Palma de Mallorca", country: "Espagne" },
  { iata: "ALC", city: "Alicante", name: "Alicante-Elche", country: "Espagne" },
  { iata: "VLC", city: "Valence", name: "Valencia", country: "Espagne" },
  { iata: "SVQ", city: "Séville", name: "San Pablo", country: "Espagne" },
  { iata: "BIO", city: "Bilbao", name: "Bilbao", country: "Espagne" },
  { iata: "TFS", city: "Tenerife", name: "Tenerife Sud", country: "Espagne" },
  { iata: "LPA", city: "Las Palmas", name: "Gran Canaria", country: "Espagne" },
  { iata: "LIS", city: "Lisbonne", name: "Humberto Delgado", country: "Portugal" },
  { iata: "OPO", city: "Porto", name: "Francisco Sá Carneiro", country: "Portugal" },
  { iata: "FAO", city: "Faro", name: "Faro", country: "Portugal" },
  { iata: "FNC", city: "Funchal", name: "Madère", country: "Portugal" },
  { iata: "FCO", city: "Rome", name: "Leonardo da Vinci Fiumicino", country: "Italie" },
  { iata: "CIA", city: "Rome", name: "Ciampino", country: "Italie" },
  { iata: "MXP", city: "Milan", name: "Malpensa", country: "Italie" },
  { iata: "LIN", city: "Milan", name: "Linate", country: "Italie" },
  { iata: "BGY", city: "Milan", name: "Bergame Orio al Serio", country: "Italie" },
  { iata: "VCE", city: "Venise", name: "Marco Polo", country: "Italie" },
  { iata: "NAP", city: "Naples", name: "Capodichino", country: "Italie" },
  { iata: "BLQ", city: "Bologne", name: "Guglielmo Marconi", country: "Italie" },
  { iata: "FLR", city: "Florence", name: "Peretola", country: "Italie" },
  { iata: "PMO", city: "Palerme", name: "Punta Raisi", country: "Italie" },
  { iata: "CTA", city: "Catane", name: "Fontanarossa", country: "Italie" },
  { iata: "ATH", city: "Athènes", name: "Elefthérios Venizélos", country: "Grèce" },
  { iata: "HER", city: "Héraklion", name: "Nikos Kazantzakis", country: "Grèce" },
  { iata: "SKG", city: "Thessalonique", name: "Makedonia", country: "Grèce" },
  { iata: "JTR", city: "Santorin", name: "Santorin", country: "Grèce" },
  { iata: "IST", city: "Istanbul", name: "Istanbul", country: "Turquie" },
  { iata: "SAW", city: "Istanbul", name: "Sabiha Gökçen", country: "Turquie" },
  { iata: "AYT", city: "Antalya", name: "Antalya", country: "Turquie" },
  { iata: "ADB", city: "Izmir", name: "Adnan Menderes", country: "Turquie" },
  { iata: "ZRH", city: "Zurich", name: "Kloten", country: "Suisse" },
  { iata: "GVA", city: "Genève", name: "Cointrin", country: "Suisse" },
  { iata: "BSL", city: "Bâle", name: "EuroAirport", country: "Suisse" },
  { iata: "VIE", city: "Vienne", name: "Schwechat", country: "Autriche" },
  { iata: "INN", city: "Innsbruck", name: "Innsbruck", country: "Autriche" },
  { iata: "CPH", city: "Copenhague", name: "Kastrup", country: "Danemark" },
  { iata: "OSL", city: "Oslo", name: "Gardermoen", country: "Norvège" },
  { iata: "BGO", city: "Bergen", name: "Flesland", country: "Norvège" },
  { iata: "ARN", city: "Stockholm", name: "Arlanda", country: "Suède" },
  { iata: "GOT", city: "Göteborg", name: "Landvetter", country: "Suède" },
  { iata: "HEL", city: "Helsinki", name: "Vantaa", country: "Finlande" },
  { iata: "KEF", city: "Reykjavik", name: "Keflavík", country: "Islande" },
  { iata: "WAW", city: "Varsovie", name: "Chopin", country: "Pologne" },
  { iata: "KRK", city: "Cracovie", name: "Jean-Paul II", country: "Pologne" },
  { iata: "PRG", city: "Prague", name: "Václav Havel", country: "Tchéquie" },
  { iata: "BUD", city: "Budapest", name: "Ferenc Liszt", country: "Hongrie" },
  { iata: "OTP", city: "Bucarest", name: "Henri Coandă", country: "Roumanie" },
  { iata: "SOF", city: "Sofia", name: "Sofia", country: "Bulgarie" },
  { iata: "BEG", city: "Belgrade", name: "Nikola Tesla", country: "Serbie" },
  { iata: "ZAG", city: "Zagreb", name: "Franjo Tuđman", country: "Croatie" },
  { iata: "DBV", city: "Dubrovnik", name: "Dubrovnik", country: "Croatie" },
  { iata: "SPU", city: "Split", name: "Split", country: "Croatie" },
  { iata: "LJU", city: "Ljubljana", name: "Jože Pučnik", country: "Slovénie" },
  { iata: "TIA", city: "Tirana", name: "Nënë Tereza", country: "Albanie" },
  { iata: "SKP", city: "Skopje", name: "Skopje", country: "Macédoine du Nord" },
  { iata: "RIX", city: "Riga", name: "Riga", country: "Lettonie" },
  { iata: "VNO", city: "Vilnius", name: "Vilnius", country: "Lituanie" },
  { iata: "TLL", city: "Tallinn", name: "Lennart Meri", country: "Estonie" },
  { iata: "KBP", city: "Kyiv", name: "Boryspil", country: "Ukraine" },
  { iata: "MSQ", city: "Minsk", name: "Minsk", country: "Biélorussie" },
  { iata: "SVO", city: "Moscou", name: "Sheremetyevo", country: "Russie" },
  { iata: "DME", city: "Moscou", name: "Domodedovo", country: "Russie" },
  { iata: "LED", city: "Saint-Pétersbourg", name: "Poulkovo", country: "Russie" },
  { iata: "TBS", city: "Tbilissi", name: "Tbilissi", country: "Géorgie" },
  { iata: "EVN", city: "Erevan", name: "Zvartnots", country: "Arménie" },
  { iata: "GYD", city: "Bakou", name: "Heydar Aliyev", country: "Azerbaïdjan" },
  { iata: "JFK", city: "New York", name: "John F. Kennedy", country: "États-Unis" },
  { iata: "EWR", city: "New York", name: "Newark Liberty", country: "États-Unis" },
  { iata: "LGA", city: "New York", name: "LaGuardia", country: "États-Unis" },
  { iata: "LAX", city: "Los Angeles", name: "Los Angeles International", country: "États-Unis" },
  { iata: "SFO", city: "San Francisco", name: "San Francisco International", country: "États-Unis" },
  { iata: "ORD", city: "Chicago", name: "O'Hare", country: "États-Unis" },
  { iata: "MDW", city: "Chicago", name: "Midway", country: "États-Unis" },
  { iata: "MIA", city: "Miami", name: "Miami International", country: "États-Unis" },
  { iata: "FLL", city: "Fort Lauderdale", name: "Hollywood", country: "États-Unis" },
  { iata: "MCO", city: "Orlando", name: "Orlando International", country: "États-Unis" },
  { iata: "ATL", city: "Atlanta", name: "Hartsfield-Jackson", country: "États-Unis" },
  { iata: "DFW", city: "Dallas", name: "Dallas/Fort Worth", country: "États-Unis" },
  { iata: "IAH", city: "Houston", name: "George Bush", country: "États-Unis" },
  { iata: "SEA", city: "Seattle", name: "Tacoma", country: "États-Unis" },
  { iata: "BOS", city: "Boston", name: "Logan", country: "États-Unis" },
  { iata: "IAD", city: "Washington", name: "Dulles", country: "États-Unis" },
  { iata: "DCA", city: "Washington", name: "Ronald Reagan", country: "États-Unis" },
  { iata: "PHL", city: "Philadelphie", name: "Philadelphia", country: "États-Unis" },
  { iata: "LAS", city: "Las Vegas", name: "Harry Reid", country: "États-Unis" },
  { iata: "PHX", city: "Phoenix", name: "Sky Harbor", country: "États-Unis" },
  { iata: "DEN", city: "Denver", name: "Denver International", country: "États-Unis" },
  { iata: "MSP", city: "Minneapolis", name: "Saint Paul", country: "États-Unis" },
  { iata: "DTW", city: "Détroit", name: "Wayne County", country: "États-Unis" },
  { iata: "CLT", city: "Charlotte", name: "Douglas International", country: "États-Unis" },
  { iata: "HNL", city: "Honolulu", name: "Daniel K. Inouye", country: "États-Unis" },
  { iata: "SAN", city: "San Diego", name: "San Diego", country: "États-Unis" },
  { iata: "YUL", city: "Montréal", name: "Pierre Elliott Trudeau", country: "Canada" },
  { iata: "YYZ", city: "Toronto", name: "Pearson", country: "Canada" },
  { iata: "YVR", city: "Vancouver", name: "Vancouver International", country: "Canada" },
  { iata: "YYC", city: "Calgary", name: "Calgary", country: "Canada" },
  { iata: "YOW", city: "Ottawa", name: "Macdonald-Cartier", country: "Canada" },
  { iata: "YQB", city: "Québec", name: "Jean Lesage", country: "Canada" },
  { iata: "MEX", city: "Mexico", name: "Benito Juárez", country: "Mexique" },
  { iata: "CUN", city: "Cancún", name: "Cancún", country: "Mexique" },
  { iata: "GDL", city: "Guadalajara", name: "Miguel Hidalgo", country: "Mexique" },
  { iata: "HAV", city: "La Havane", name: "José Martí", country: "Cuba" },
  { iata: "PUJ", city: "Punta Cana", name: "Punta Cana", country: "République dominicaine" },
  { iata: "SDQ", city: "Saint-Domingue", name: "Las Américas", country: "République dominicaine" },
  { iata: "NAS", city: "Nassau", name: "Lynden Pindling", country: "Bahamas" },
  { iata: "MBJ", city: "Montego Bay", name: "Sangster", country: "Jamaïque" },
  { iata: "GRU", city: "São Paulo", name: "Guarulhos", country: "Brésil" },
  { iata: "CGH", city: "São Paulo", name: "Congonhas", country: "Brésil" },
  { iata: "GIG", city: "Rio de Janeiro", name: "Galeão", country: "Brésil" },
  { iata: "BSB", city: "Brasilia", name: "Presidente Juscelino Kubitschek", country: "Brésil" },
  { iata: "SSA", city: "Salvador", name: "Deputado Luís Eduardo Magalhães", country: "Brésil" },
  { iata: "EZE", city: "Buenos Aires", name: "Ministro Pistarini Ezeiza", country: "Argentine" },
  { iata: "AEP", city: "Buenos Aires", name: "Jorge Newbery", country: "Argentine" },
  { iata: "SCL", city: "Santiago", name: "Arturo Merino Benítez", country: "Chili" },
  { iata: "LIM", city: "Lima", name: "Jorge Chávez", country: "Pérou" },
  { iata: "BOG", city: "Bogotá", name: "El Dorado", country: "Colombie" },
  { iata: "MDE", city: "Medellín", name: "José María Córdova", country: "Colombie" },
  { iata: "UIO", city: "Quito", name: "Mariscal Sucre", country: "Équateur" },
  { iata: "CCS", city: "Caracas", name: "Simón Bolívar", country: "Venezuela" },
  { iata: "PTY", city: "Panama", name: "Tocumen", country: "Panama" },
  { iata: "SJO", city: "San José", name: "Juan Santamaría", country: "Costa Rica" },
  { iata: "MVD", city: "Montevideo", name: "Carrasco", country: "Uruguay" },
  { iata: "ASU", city: "Asunción", name: "Silvio Pettirossi", country: "Paraguay" },
  { iata: "LPB", city: "La Paz", name: "El Alto", country: "Bolivie" },
  { iata: "CMN", city: "Casablanca", name: "Mohammed V", country: "Maroc" },
  { iata: "RAK", city: "Marrakech", name: "Ménara", country: "Maroc" },
  { iata: "AGA", city: "Agadir", name: "Al Massira", country: "Maroc" },
  { iata: "TNG", city: "Tanger", name: "Ibn Battouta", country: "Maroc" },
  { iata: "FEZ", city: "Fès", name: "Fès-Saïss", country: "Maroc" },
  { iata: "RBA", city: "Rabat", name: "Salé", country: "Maroc" },
  { iata: "OUD", city: "Oujda", name: "Angads", country: "Maroc" },
  { iata: "TUN", city: "Tunis", name: "Carthage", country: "Tunisie" },
  { iata: "DJE", city: "Djerba", name: "Zarzis", country: "Tunisie" },
  { iata: "MIR", city: "Monastir", name: "Habib Bourguiba", country: "Tunisie" },
  { iata: "ALG", city: "Alger", name: "Houari Boumédiène", country: "Algérie" },
  { iata: "ORN", city: "Oran", name: "Ahmed Ben Bella", country: "Algérie" },
  { iata: "CZL", city: "Constantine", name: "Mohamed Boudiaf", country: "Algérie" },
  { iata: "CAI", city: "Le Caire", name: "Le Caire International", country: "Égypte" },
  { iata: "HRG", city: "Hurghada", name: "Hurghada", country: "Égypte" },
  { iata: "SSH", city: "Charm el-Cheikh", name: "Sharm El Sheikh", country: "Égypte" },
  { iata: "ALY", city: "Alexandrie", name: "El Nouzha", country: "Égypte" },
  { iata: "PTP", city: "Pointe-à-Pitre", name: "Pôle Caraïbes", country: "Guadeloupe" },
  { iata: "FDF", city: "Fort-de-France", name: "Aimé Césaire", country: "Martinique" },
  { iata: "DKR", city: "Dakar", name: "Blaise Diagne", country: "Sénégal" },
  { iata: "ABJ", city: "Abidjan", name: "Félix Houphouët-Boigny", country: "Côte d'Ivoire" },
  { iata: "ACC", city: "Accra", name: "Kotoka", country: "Ghana" },
  { iata: "LOS", city: "Lagos", name: "Murtala Muhammed", country: "Nigeria" },
  { iata: "ABV", city: "Abuja", name: "Nnamdi Azikiwe", country: "Nigeria" },
  { iata: "COO", city: "Cotonou", name: "Cadjehoun", country: "Bénin" },
  { iata: "LFW", city: "Lomé", name: "Gnassingbé Eyadéma", country: "Togo" },
  { iata: "OUA", city: "Ouagadougou", name: "Ouagadougou", country: "Burkina Faso" },
  { iata: "BKO", city: "Bamako", name: "Modibo Keïta", country: "Mali" },
  { iata: "NKC", city: "Nouakchott", name: "Oumtounsy", country: "Mauritanie" },
  { iata: "CKY", city: "Conakry", name: "Ahmed Sékou Touré", country: "Guinée" },
  { iata: "FNA", city: "Freetown", name: "Lungi", country: "Sierra Leone" },
  { iata: "ROB", city: "Monrovia", name: "Roberts", country: "Liberia" },
  { iata: "DLA", city: "Douala", name: "Douala", country: "Cameroun" },
  { iata: "YAO", city: "Yaoundé", name: "Nsimalen", country: "Cameroun" },
  { iata: "LBV", city: "Libreville", name: "Léon Mba", country: "Gabon" },
  { iata: "BGF", city: "Bangui", name: "M'Poko", country: "Centrafrique" },
  { iata: "NDJ", city: "N'Djamena", name: "Hassan Djamous", country: "Tchad" },
  { iata: "FIH", city: "Kinshasa", name: "N'djili", country: "RD Congo" },
  { iata: "BZV", city: "Brazzaville", name: "Maya-Maya", country: "Congo" },
  { iata: "PNR", city: "Pointe-Noire", name: "Agostinho-Neto", country: "Congo" },
  { iata: "LAD", city: "Luanda", name: "Quatro de Fevereiro", country: "Angola" },
  { iata: "NBO", city: "Nairobi", name: "Jomo Kenyatta", country: "Kenya" },
  { iata: "MBA", city: "Mombasa", name: "Moi", country: "Kenya" },
  { iata: "ADD", city: "Addis-Abeba", name: "Bole", country: "Éthiopie" },
  { iata: "DAR", city: "Dar es Salaam", name: "Julius Nyerere", country: "Tanzanie" },
  { iata: "JRO", city: "Kilimandjaro", name: "Kilimanjaro", country: "Tanzanie" },
  { iata: "EBB", city: "Entebbe", name: "Entebbe", country: "Ouganda" },
  { iata: "KGL", city: "Kigali", name: "Kigali International", country: "Rwanda" },
  { iata: "BJM", city: "Bujumbura", name: "Bujumbura", country: "Burundi" },
  { iata: "JNB", city: "Johannesburg", name: "O.R. Tambo", country: "Afrique du Sud" },
  { iata: "CPT", city: "Le Cap", name: "Cape Town International", country: "Afrique du Sud" },
  { iata: "DUR", city: "Durban", name: "King Shaka", country: "Afrique du Sud" },
  { iata: "WDH", city: "Windhoek", name: "Hosea Kutako", country: "Namibie" },
  { iata: "GBE", city: "Gaborone", name: "Sir Seretse Khama", country: "Botswana" },
  { iata: "HRE", city: "Harare", name: "Robert Gabriel Mugabe", country: "Zimbabwe" },
  { iata: "LUN", city: "Lusaka", name: "Kenneth Kaunda", country: "Zambie" },
  { iata: "MPM", city: "Maputo", name: "Maputo", country: "Mozambique" },
  { iata: "TNR", city: "Antananarivo", name: "Ivato", country: "Madagascar" },
  { iata: "MRU", city: "Port-Louis", name: "Sir Seewoosagur Ramgoolam", country: "Maurice" },
  { iata: "SEZ", city: "Mahé", name: "Seychelles", country: "Seychelles" },
  { iata: "RUN", city: "Saint-Denis", name: "Roland Garros", country: "La Réunion" },
  { iata: "DZA", city: "Dzaoudzi", name: "Pamandzi", country: "Mayotte" },
  { iata: "DXB", city: "Dubaï", name: "Dubaï International", country: "Émirats arabes unis" },
  { iata: "DWC", city: "Dubaï", name: "Al Maktoum", country: "Émirats arabes unis" },
  { iata: "AUH", city: "Abou Dabi", name: "Zayed International", country: "Émirats arabes unis" },
  { iata: "SHJ", city: "Charjah", name: "Sharjah", country: "Émirats arabes unis" },
  { iata: "DOH", city: "Doha", name: "Hamad International", country: "Qatar" },
  { iata: "RUH", city: "Riyad", name: "King Khalid", country: "Arabie saoudite" },
  { iata: "JED", city: "Djeddah", name: "King Abdulaziz", country: "Arabie saoudite" },
  { iata: "MED", city: "Médine", name: "Prince Mohammad Bin Abdulaziz", country: "Arabie saoudite" },
  { iata: "MCT", city: "Mascate", name: "Muscat", country: "Oman" },
  { iata: "BAH", city: "Manama", name: "Bahreïn", country: "Bahreïn" },
  { iata: "KWI", city: "Koweït", name: "Kuwait International", country: "Koweït" },
  { iata: "AMM", city: "Amman", name: "Queen Alia", country: "Jordanie" },
  { iata: "BEY", city: "Beyrouth", name: "Rafic Hariri", country: "Liban" },
  { iata: "TLV", city: "Tel Aviv", name: "Ben Gourion", country: "Israël" },
  { iata: "BGW", city: "Bagdad", name: "Baghdad", country: "Irak" },
  { iata: "EBL", city: "Erbil", name: "Erbil", country: "Irak" },
  { iata: "THR", city: "Téhéran", name: "Imam Khomeini", country: "Iran" },
  { iata: "IKA", city: "Téhéran", name: "Imam Khomeini", country: "Iran" },
  { iata: "NRT", city: "Tokyo", name: "Narita", country: "Japon" },
  { iata: "HND", city: "Tokyo", name: "Haneda", country: "Japon" },
  { iata: "KIX", city: "Osaka", name: "Kansai", country: "Japon" },
  { iata: "ITM", city: "Osaka", name: "Itami", country: "Japon" },
  { iata: "NGO", city: "Nagoya", name: "Chubu Centrair", country: "Japon" },
  { iata: "FUK", city: "Fukuoka", name: "Fukuoka", country: "Japon" },
  { iata: "CTS", city: "Sapporo", name: "New Chitose", country: "Japon" },
  { iata: "ICN", city: "Séoul", name: "Incheon", country: "Corée du Sud" },
  { iata: "GMP", city: "Séoul", name: "Gimpo", country: "Corée du Sud" },
  { iata: "PUS", city: "Busan", name: "Gimhae", country: "Corée du Sud" },
  { iata: "PEK", city: "Pékin", name: "Capitale", country: "Chine" },
  { iata: "PKX", city: "Pékin", name: "Daxing", country: "Chine" },
  { iata: "PVG", city: "Shanghai", name: "Pudong", country: "Chine" },
  { iata: "SHA", city: "Shanghai", name: "Hongqiao", country: "Chine" },
  { iata: "CAN", city: "Canton", name: "Baiyun", country: "Chine" },
  { iata: "SZX", city: "Shenzhen", name: "Bao'an", country: "Chine" },
  { iata: "CTU", city: "Chengdu", name: "Shuangliu", country: "Chine" },
  { iata: "TFU", city: "Chengdu", name: "Tianfu", country: "Chine" },
  { iata: "HGH", city: "Hangzhou", name: "Xiaoshan", country: "Chine" },
  { iata: "XIY", city: "Xi'an", name: "Xianyang", country: "Chine" },
  { iata: "CKG", city: "Chongqing", name: "Jiangbei", country: "Chine" },
  { iata: "HKG", city: "Hong Kong", name: "Chek Lap Kok", country: "Hong Kong" },
  { iata: "MFM", city: "Macao", name: "Macao", country: "Macao" },
  { iata: "TPE", city: "Taipei", name: "Taoyuan", country: "Taïwan" },
  { iata: "TSA", city: "Taipei", name: "Songshan", country: "Taïwan" },
  { iata: "MNL", city: "Manille", name: "Ninoy Aquino", country: "Philippines" },
  { iata: "CEB", city: "Cebu", name: "Mactan-Cebu", country: "Philippines" },
  { iata: "CGK", city: "Jakarta", name: "Soekarno-Hatta", country: "Indonésie" },
  { iata: "DPS", city: "Denpasar", name: "Ngurah Rai Bali", country: "Indonésie" },
  { iata: "SUB", city: "Surabaya", name: "Juanda", country: "Indonésie" },
  { iata: "KUL", city: "Kuala Lumpur", name: "Kuala Lumpur International", country: "Malaisie" },
  { iata: "SZB", city: "Kuala Lumpur", name: "Sultan Abdul Aziz Shah", country: "Malaisie" },
  { iata: "PEN", city: "Penang", name: "Penang", country: "Malaisie" },
  { iata: "SIN", city: "Singapour", name: "Changi", country: "Singapour" },
  { iata: "BKK", city: "Bangkok", name: "Suvarnabhumi", country: "Thaïlande" },
  { iata: "DMK", city: "Bangkok", name: "Don Mueang", country: "Thaïlande" },
  { iata: "HKT", city: "Phuket", name: "Phuket", country: "Thaïlande" },
  { iata: "CNX", city: "Chiang Mai", name: "Chiang Mai", country: "Thaïlande" },
  { iata: "SGN", city: "Hô Chi Minh-Ville", name: "Tân Sơn Nhất", country: "Viêt Nam" },
  { iata: "HAN", city: "Hanoï", name: "Nội Bài", country: "Viêt Nam" },
  { iata: "DAD", city: "Đà Nẵng", name: "Đà Nẵng", country: "Viêt Nam" },
  { iata: "PNH", city: "Phnom Penh", name: "Phnom Penh", country: "Cambodge" },
  { iata: "REP", city: "Siem Reap", name: "Angkor", country: "Cambodge" },
  { iata: "VTE", city: "Vientiane", name: "Wattay", country: "Laos" },
  { iata: "RGN", city: "Yangon", name: "Yangon", country: "Myanmar" },
  { iata: "DEL", city: "Delhi", name: "Indira Gandhi", country: "Inde" },
  { iata: "BOM", city: "Mumbai", name: "Chhatrapati Shivaji", country: "Inde" },
  { iata: "BLR", city: "Bengaluru", name: "Kempegowda", country: "Inde" },
  { iata: "MAA", city: "Chennai", name: "Chennai", country: "Inde" },
  { iata: "HYD", city: "Hyderabad", name: "Rajiv Gandhi", country: "Inde" },
  { iata: "CCU", city: "Kolkata", name: "Netaji Subhas Chandra Bose", country: "Inde" },
  { iata: "GOI", city: "Goa", name: "Dabolim", country: "Inde" },
  { iata: "COK", city: "Kochi", name: "Cochin", country: "Inde" },
  { iata: "CMB", city: "Colombo", name: "Bandaranaike", country: "Sri Lanka" },
  { iata: "DAC", city: "Dacca", name: "Hazrat Shahjalal", country: "Bangladesh" },
  { iata: "KTM", city: "Katmandou", name: "Tribhuvan", country: "Népal" },
  { iata: "ISB", city: "Islamabad", name: "Islamabad International", country: "Pakistan" },
  { iata: "KHI", city: "Karachi", name: "Jinnah", country: "Pakistan" },
  { iata: "LHE", city: "Lahore", name: "Allama Iqbal", country: "Pakistan" },
  { iata: "KBL", city: "Kaboul", name: "Hamid Karzai", country: "Afghanistan" },
  { iata: "TAS", city: "Tachkent", name: "Islam Karimov", country: "Ouzbékistan" },
  { iata: "ALA", city: "Almaty", name: "Almaty", country: "Kazakhstan" },
  { iata: "NQZ", city: "Astana", name: "Noursoultan Nazarbaïev", country: "Kazakhstan" },
  { iata: "FRU", city: "Bichkek", name: "Manas", country: "Kirghizistan" },
  { iata: "ULN", city: "Oulan-Bator", name: "Chinggis Khaan", country: "Mongolie" },
  { iata: "SYD", city: "Sydney", name: "Kingsford Smith", country: "Australie" },
  { iata: "MEL", city: "Melbourne", name: "Tullamarine", country: "Australie" },
  { iata: "BNE", city: "Brisbane", name: "Brisbane", country: "Australie" },
  { iata: "PER", city: "Perth", name: "Perth", country: "Australie" },
  { iata: "ADL", city: "Adélaïde", name: "Adelaide", country: "Australie" },
  { iata: "CNS", city: "Cairns", name: "Cairns", country: "Australie" },
  { iata: "AKL", city: "Auckland", name: "Auckland", country: "Nouvelle-Zélande" },
  { iata: "WLG", city: "Wellington", name: "Wellington", country: "Nouvelle-Zélande" },
  { iata: "CHC", city: "Christchurch", name: "Christchurch", country: "Nouvelle-Zélande" },
  { iata: "NAN", city: "Nadi", name: "Nadi", country: "Fidji" },
  { iata: "PPT", city: "Papeete", name: "Faa'a", country: "Polynésie française" },
  { iata: "NOU", city: "Nouméa", name: "La Tontouta", country: "Nouvelle-Calédonie" },
  { iata: "GUM", city: "Guam", name: "Antonio B. Won Pat", country: "Guam" },
];

const unique = new Map<string, Airport>();
for (const airport of AIRPORTS) unique.set(airport.iata, airport);
export const AIRPORT_INDEX = unique;

export function getAirport(iata: string) {
  return AIRPORT_INDEX.get(iata.trim().toUpperCase());
}

export function formatAirportLabel(airport: Airport) {
  return `${airport.city} — ${airport.name} (${airport.iata})`;
}

export function searchAirports(query: string, limit = 12): Airport[] {
  const q = query.trim().toLowerCase().replace(/[—–]/g, " ");
  if (!q) {
    return POPULAR_IATA.map((code) => AIRPORT_INDEX.get(code)).filter(Boolean) as Airport[];
  }
  const scored = [...AIRPORT_INDEX.values()]
    .map((airport) => {
      const iata = airport.iata.toLowerCase();
      const city = airport.city.toLowerCase();
      const name = airport.name.toLowerCase();
      const country = airport.country.toLowerCase();
      let score = 0;
      if (iata === q) score = 100;
      else if (iata.startsWith(q)) score = 80;
      else if (city.startsWith(q)) score = 70;
      else if (name.startsWith(q)) score = 60;
      else if (city.includes(q) || name.includes(q) || country.includes(q) || iata.includes(q)) score = 30;
      return { airport, score };
    })
    .filter((row) => row.score > 0)
    .sort((a, b) => b.score - a.score || a.airport.city.localeCompare(b.airport.city));
  return scored.slice(0, limit).map((row) => row.airport);
}
