export const DESTINATIONS = [
  {
    slug: "paris-new-york",
    title: "Paris → New York",
    from: "CDG",
    to: "JFK",
    blurb: "Le classique transatlantique : comparer les long-courriers sans payer plus cher.",
    highlight: "Vols dès ~450 € A/R hors saison",
  },
  {
    slug: "paris-marrakech",
    title: "Paris → Marrakech",
    from: "ORY",
    to: "RAK",
    blurb: "Week-end soleil : low-cost et compagnies régulières sur la même page.",
    highlight: "Souvent moins de 3 h de vol",
  },
  {
    slug: "paris-dakar",
    title: "Paris → Dakar",
    from: "CDG",
    to: "DKR",
    blurb: "Liaisons fréquentes vers l’Afrique de l’Ouest, avec correspondances ou directs.",
    highlight: "Idéal pour un séjour famille ou affaires",
  },
  {
    slug: "lyon-lisbonne",
    title: "Lyon → Lisbonne",
    from: "LYS",
    to: "LIS",
    blurb: "City-break atlantique : TAP, easyJet et Transavia en un coup d’œil.",
    highlight: "Parfait pour 3 à 4 jours",
  },
  {
    slug: "paris-tokyo",
    title: "Paris → Tokyo",
    from: "CDG",
    to: "NRT",
    blurb: "Long-courrier Asie : comparez durées, escales et compagnies premium.",
    highlight: "Attention aux saisons (cerisiers, Golden Week)",
  },
  {
    slug: "nice-londres",
    title: "Nice → Londres",
    from: "NCE",
    to: "LHR",
    blurb: "Navette Côte d’Azur : horaires tôt le matin et retours en soirée.",
    highlight: "Aller simple fréquent toute l’année",
  },
] as const;
