export const DESTINATIONS = [
  {
    slug: "paris-marrakech",
    title: "Paris → Marrakech",
    from: "ORY",
    to: "RAK",
    blurb: "Week-end soleil : low-cost et compagnies régulières sur la même page.",
    highlight: "Souvent moins de 3 h de vol",
    avgFare: 92,
  },
  {
    slug: "marseille-alger",
    title: "Marseille → Alger",
    from: "MRS",
    to: "ALG",
    blurb: "Liaison Maghreb très fréquentée : Air Algérie, Transavia et low-cost comparés.",
    highlight: "Vols souvent inférieurs à 2 h",
    avgFare: 78,
  },
  {
    slug: "paris-montreal",
    title: "Paris → Montréal",
    from: "CDG",
    to: "YUL",
    blurb: "Transatlantique francophone : Air France, Air Canada et partenaires en un coup d’œil.",
    highlight: "Meilleure fenêtre : avril–juin et septembre",
    avgFare: 445,
  },
  {
    slug: "paris-new-york",
    title: "Paris → New York",
    from: "CDG",
    to: "JFK",
    blurb: "Le classique transatlantique : comparer les long-courriers sans payer plus cher.",
    highlight: "Vols dès ~450 € A/R hors saison",
    avgFare: 468,
  },
  {
    slug: "paris-dakar",
    title: "Paris → Dakar",
    from: "CDG",
    to: "DKR",
    blurb: "Liaisons fréquentes vers l’Afrique de l’Ouest, avec correspondances ou directs.",
    highlight: "Idéal pour un séjour famille ou affaires",
    avgFare: 312,
  },
  {
    slug: "lyon-lisbonne",
    title: "Lyon → Lisbonne",
    from: "LYS",
    to: "LIS",
    blurb: "City-break atlantique : TAP, easyJet et Transavia en un coup d’œil.",
    highlight: "Parfait pour 3 à 4 jours",
    avgFare: 86,
  },
  {
    slug: "paris-tokyo",
    title: "Paris → Tokyo",
    from: "CDG",
    to: "NRT",
    blurb: "Long-courrier Asie : comparez durées, escales et compagnies premium.",
    highlight: "Attention aux saisons (cerisiers, Golden Week)",
    avgFare: 720,
  },
  {
    slug: "nice-londres",
    title: "Nice → Londres",
    from: "NCE",
    to: "LHR",
    blurb: "Navette Côte d’Azur : horaires tôt le matin et retours en soirée.",
    highlight: "Aller simple fréquent toute l’année",
    avgFare: 64,
  },
] as const;
